#!/usr/bin/env python3
"""Select and download a deterministic public-domain Met artwork for one day."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
MET_API = "https://collectionapi.metmuseum.org/public/collection/v1"
USER_AGENT = "depository-daily-art/1.0"
MAX_CANDIDATES = 64
FRAME_NAMES = ("gilt", "bracket", "mat", "engraved")


def request_json(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def download_image(url: str, destination: Path) -> None:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        content_type = response.headers.get_content_type()
        if not content_type.startswith("image/"):
            raise ValueError(f"Met returned {content_type}, not an image")
        with tempfile.NamedTemporaryFile(dir=destination.parent, delete=False) as temporary:
            temporary.write(response.read())
            temporary_path = Path(temporary.name)
    temporary_path.replace(destination)


def yaml_string(value: str) -> str:
    """JSON strings are valid YAML strings and handle museum punctuation safely."""
    return json.dumps(value, ensure_ascii=False)


def frame_name(object_id: int) -> str:
    """Choose a stable ornamental frame for one artwork."""
    digest = hashlib.sha256(str(object_id).encode()).digest()
    return FRAME_NAMES[digest[0] % len(FRAME_NAMES)]


def select_artwork(day: dt.date) -> dict:
    query = urllib.parse.urlencode(
        {
            "q": "painting",
            "hasImages": "true",
            "isHighlight": "true",
        }
    )
    search = request_json(f"{MET_API}/search?{query}")
    object_ids = search.get("objectIDs") or []
    if not object_ids:
        raise RuntimeError("The Met search returned no highlight artworks")

    start = int.from_bytes(
        hashlib.sha256(day.isoformat().encode()).digest()[:8], "big"
    ) % len(object_ids)
    for offset in range(min(MAX_CANDIDATES, len(object_ids))):
        object_id = object_ids[(start + offset) % len(object_ids)]
        artwork = request_json(f"{MET_API}/objects/{object_id}")
        if artwork.get("isPublicDomain") and artwork.get("primaryImageSmall"):
            return artwork
    raise RuntimeError("No usable public-domain artwork found near the daily selection")


def write_metadata(day: dt.date, artwork: dict) -> None:
    image_path = REPO_ROOT / "static" / "images" / "daily_art.jpg"
    download_image(artwork["primaryImageSmall"], image_path)

    title = artwork.get("title") or "Untitled"
    artist = artwork.get("artistDisplayName") or "Unknown artist"
    object_date = artwork.get("objectDate") or "Undated"
    medium = artwork.get("medium") or "Medium not listed"
    object_url = artwork["objectURL"]
    daily_art = "\n".join(
        [
            "# Generated by scripts/refresh_daily_art.py; do not edit by hand.",
            f"date: {yaml_string(day.isoformat())}",
            f"object_id: {artwork['objectID']}",
            f"frame: {frame_name(artwork['objectID'])}",
            f"title: {yaml_string(title)}",
            f"artist: {yaml_string(artist)}",
            f"object_date: {yaml_string(object_date)}",
            f"medium: {yaml_string(medium)}",
            f"object_url: {yaml_string(object_url)}",
            'image: "/images/daily_art.jpg"',
            "",
        ]
    )
    write_text(REPO_ROOT / "data" / "daily_art.yaml", daily_art)
    write_text(
        REPO_ROOT / "data" / "site_refresh.yaml",
        "# Generated by scripts/refresh_daily_art.py; do not edit by hand.\n"
        f"date: {yaml_string(day.isoformat())}\n",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--date",
        type=dt.date.fromisoformat,
        default=dt.datetime.now(dt.UTC).date(),
        help="UTC date to select, in YYYY-MM-DD form",
    )
    arguments = parser.parse_args()
    artwork = select_artwork(arguments.date)
    write_metadata(arguments.date, artwork)
    print(
        f"{arguments.date}: {artwork['title']} by "
        f"{artwork.get('artistDisplayName') or 'Unknown artist'} "
        f"(Met object {artwork['objectID']})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
